const initialEvents = [
  {id:'c1',sport:'Cricket',league:'T20 INTERNATIONAL',live:true,time:'17.3 ov',home:'West Indies',away:'New Zealand',scoreA:'146/4',scoreB:'—',meta:'Run rate 8.34',markets:42,odds:[2.18,7.90,1.73],suspended:false},
  {id:'c2',sport:'Cricket',league:'MAJOR LEAGUE CRICKET',live:true,time:'8.1 ov',home:'San Francisco Unicorns',away:'Washington Freedom',scoreA:'72/2',scoreB:'—',meta:'Run rate 8.81',markets:36,odds:[1.62,9.20,2.34],suspended:false},
  {id:'c3',sport:'Cricket',league:'VITALITY BLAST WOMEN',live:false,time:'Today · 15:30',home:'Surrey Women',away:'The Blaze Women',scoreA:'',scoreB:'',meta:'Match winner',markets:28,odds:[1.86,12,1.95],suspended:false},
  {id:'f1',sport:'Football',league:'WORLD CLUB SERIES',live:true,time:'67′',home:'Madrid White',away:'London Blue',scoreA:'2',scoreB:'1',meta:'Shots 11–7 · Corners 5–3',markets:61,odds:[1.44,4.60,9.50],suspended:false},
  {id:'f2',sport:'Football',league:'EUROPEAN QUALIFIERS',live:false,time:'Today · 20:00',home:'North City',away:'United Athletic',scoreA:'',scoreB:'',meta:'Match result',markets:74,odds:[2.35,3.30,2.92],suspended:false},
  {id:'t1',sport:'Tennis',league:'ATP BASTAD',live:true,time:'Set 2',home:'A. Romero',away:'J. Lind',scoreA:'6 2',scoreB:'4 3',meta:'Romero serving · 30–15',markets:24,odds:[1.31,0,3.45],suspended:false}
];
let events = structuredClone(initialEvents);
let selectedSport = 'All'; let liveOnly = false; let selections = []; let balance = Number(localStorage.getItem('scorexBalance') || 25000);
let openBets = JSON.parse(localStorage.getItem('scorexOpenBets') || '[]');
let admins = JSON.parse(localStorage.getItem('scorexAdmins') || JSON.stringify([
  {id:1,name:'Atul Singh',email:'superadmin@scorex.demo',role:'SUPER_ADMIN',active:true,last:'Just now'},
  {id:2,name:'Priya Sharma',email:'markets@scorex.demo',role:'MARKET_MANAGER',active:true,last:'2 hours ago'},
  {id:3,name:'Rahul Verma',email:'support@scorex.demo',role:'SUPPORT_AGENT',active:true,last:'Yesterday'}
]));
let audit = JSON.parse(localStorage.getItem('scorexAudit') || JSON.stringify([{action:'Super Admin signed in to the demo console',time:'Just now'}]));
const el = id => document.getElementById(id);
function coin(n){return `${Math.round(n).toLocaleString()} SXC`}
function save(){localStorage.setItem('scorexBalance',balance);localStorage.setItem('scorexOpenBets',JSON.stringify(openBets));localStorage.setItem('scorexAdmins',JSON.stringify(admins));localStorage.setItem('scorexAudit',JSON.stringify(audit));}
function showToast(message){el('toast').textContent='✓ '+message;el('toast').classList.remove('hidden');setTimeout(()=>el('toast').classList.add('hidden'),2400)}
function filtered(){return events.filter(e=>(selectedSport==='All'||e.sport===selectedSport)&&(!liveOnly||e.live));}
function renderEvents(){el('marketTitle').textContent=liveOnly?'Live events':selectedSport==='All'?'Featured events':selectedSport;el('eventList').innerHTML=filtered().map(e=>`<article class="event"><div><div class="league"><span>${e.sport}</span>${e.league}${e.live?'<b class="live-label">● LIVE</b>':''}</div><div class="teams"><div><strong>${e.home}</strong><b>${e.scoreA}</b></div><div><strong>${e.away}</strong><b>${e.scoreB}</b></div></div><div class="meta">${e.time} · ${e.meta}</div></div>${e.odds.map((odd,i)=>odd?`<button class="price ${selections.some(s=>s.id===`${e.id}-${i}`)?'selected':''}" ${e.suspended?'disabled':''} data-pick="${e.id}-${i}"><small>${['1','X','2'][i]}</small>${e.suspended?'Suspended':odd.toFixed(2)}</button>`:'<button class="price" disabled><small>—</small>—</button>').join('')}<button class="market-count">+${e.markets}<small>markets</small></button></article>`).join('');document.querySelectorAll('[data-pick]').forEach(btn=>btn.onclick=()=>selectPick(btn.dataset.pick));}
function selectPick(key){const [eventId,indexText]=key.split('-');const index=Number(indexText);const event=events.find(e=>e.id===eventId);const labels=event.sport==='Tennis'?[event.home,'',event.away]:[event.home,'Draw',event.away];const pick={id:key,eventId,match:`${event.home} v ${event.away}`,label:labels[index],market:'Match result',odds:event.odds[index]};selections=selections.some(s=>s.id===key)?selections.filter(s=>s.id!==key):[...selections.filter(s=>s.eventId!==eventId),pick];renderEvents();renderSlip();}
function renderSlip(){const stake=Number(el('stake').value||0);const odds=selections.reduce((total,s)=>total*s.odds,1);const potential=selections.length?stake*odds:0;el('balance').textContent=coin(balance);el('slipCount').textContent=selections.length;el('potentialReturn').textContent=coin(potential);el('emptySlip').classList.toggle('hidden',selections.length>0);el('slipItems').innerHTML=selections.map(s=>`<div class="slip-item"><button class="remove" data-remove="${s.id}">×</button><small>${s.market}</small><strong>${s.label}</strong><p>${s.match}</p><b>${s.odds.toFixed(2)}</b></div>`).join('');el('placeBet').disabled=!selections.length||stake<=0||stake>balance;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selections=selections.filter(s=>s.id!==b.dataset.remove);renderEvents();renderSlip()});}
function renderOpen(){el('openCount').textContent=openBets.length;el('openBets').innerHTML=openBets.length?openBets.map(b=>`<article class="open-bet"><span>OPEN · VIRTUAL</span><strong>${b.label} @ ${b.odds.toFixed(2)}</strong><p>${b.match}</p><small>Stake ${coin(b.stake)} · Potential ${coin(b.return)}</small></article>`).join(''):'<div class="empty"><div>⌁</div><h3>No open bets</h3><p>Accepted virtual bets appear here.</p></div>';}
function placeBet(){const stake=Number(el('stake').value);const odds=selections.reduce((t,s)=>t*s.odds,1);balance-=stake;openBets.unshift({...selections[0],label:selections.length>1?`${selections.length}-fold accumulator`:selections[0].label,odds,stake,return:stake*odds});audit.unshift({action:`Placed a ${selections.length}-selection virtual bet`,time:'Just now'});selections=[];save();renderEvents();renderSlip();renderOpen();showToast('Virtual bet accepted');document.querySelector('[data-tab="open"]').click();}
function log(action){audit.unshift({action,time:'Just now'});save();renderAdmin();showToast(action)}
function renderAdmin(){el('adminList').innerHTML=admins.map(a=>`<div class="admin-row"><div class="admin-avatar">${a.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>${a.name}</strong><small>${a.email} · Last login ${a.last}</small></div><span class="badge ${a.active?'':'off'}">${a.active?a.role:'DEACTIVATED'}</span>${a.role!=='SUPER_ADMIN'?`<button class="deactivate" data-admin="${a.id}">${a.active?'Deactivate':'Reactivate'}</button>`:''}</div>`).join('');el('auditLog').innerHTML=audit.slice(0,8).map(x=>`<div class="audit-item">${x.action}<small>${x.time}</small></div>`).join('');el('marketControls').innerHTML=events.filter(e=>e.live).map(e=>`<div class="market-row"><div><strong>${e.home} v ${e.away}</strong><small>${e.sport} · ${e.league}</small></div><span class="badge ${e.suspended?'off':''}">${e.suspended?'SUSPENDED':'ACTIVE'}</span><button class="suspend" data-market="${e.id}">${e.suspended?'Resume':'Suspend'}</button></div>`).join('');document.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>{const a=admins.find(x=>x.id===Number(b.dataset.admin));a.active=!a.active;log(`${a.active?'Reactivated':'Deactivated'} admin account: ${a.email}`)});document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>{const e=events.find(x=>x.id===b.dataset.market);e.suspended=!e.suspended;log(`${e.suspended?'Suspended':'Resumed'} market: ${e.home} v ${e.away}`);renderEvents()});}
document.querySelectorAll('.sport-filter').forEach(b=>b.onclick=()=>{selectedSport=b.dataset.sport;liveOnly=false;el('liveToggle').checked=false;document.querySelectorAll('.sport-filter').forEach(x=>x.classList.toggle('selected',x===b));renderEvents()});
el('liveToggle').onchange=e=>{liveOnly=e.target.checked;renderEvents()};el('liveOnlyButton').onclick=()=>{liveOnly=true;el('liveToggle').checked=true;renderEvents()};el('heroLiveButton').onclick=el('liveOnlyButton').onclick;el('clearFilterButton').onclick=()=>{liveOnly=false;selectedSport='All';el('liveToggle').checked=false;document.querySelectorAll('.sport-filter').forEach(x=>x.classList.toggle('selected',x.dataset.sport==='All'));renderEvents()};
document.querySelectorAll('[data-stake]').forEach(b=>b.onclick=()=>{el('stake').value=b.dataset.stake;renderSlip()});el('stake').oninput=renderSlip;el('placeBet').onclick=placeBet;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));el('slipPanel').classList.toggle('hidden',b.dataset.tab!=='slip');el('openPanel').classList.toggle('hidden',b.dataset.tab!=='open')});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const admin=b.dataset.view==='admin';el('sports').classList.toggle('hidden',admin);el('admin').classList.toggle('hidden',!admin);document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x===b));if(admin)renderAdmin()});el('backToSports').onclick=()=>document.querySelector('[data-view="sports"]').click();
el('newAdminButton').onclick=()=>el('adminDialog').showModal();el('adminForm').addEventListener('submit',e=>{e.preventDefault();admins.push({id:Date.now(),name:el('adminName').value,email:el('adminEmail').value,role:el('adminRole').value,active:true,last:'Never'});el('adminDialog').close();e.target.reset();log(`Created ${admins.at(-1).role} account: ${admins.at(-1).email}`)});
setInterval(()=>{const active=events.filter(e=>e.live&&!e.suspended);if(!active.length)return;const event=active[Math.floor(Math.random()*active.length)];event.odds=event.odds.map((o,i)=>o?Math.max(1.05,+(o+(i===0?-.02:.03)).toFixed(2)):0);if(event.id==='c1'){const run=140+Math.floor(Math.random()*20);event.scoreA=`${run}/${3+Math.floor(Math.random()*3)}`;el('heroRuns').textContent=event.scoreA;el('heroOvers').textContent=`${17+Math.floor(Math.random()*3)}.${Math.floor(Math.random()*6)} overs`}renderEvents()},4000);
renderEvents();renderSlip();renderOpen();renderAdmin();
