export interface AppElements {
  sportsView: HTMLElement;
  adminView: HTMLElement;
  marketTitle: HTMLElement;
  scheduleFilters: HTMLElement;
  eventSummary: HTMLElement;
  eventList: HTMLElement;
  feedLabel: HTMLElement;
  feedMessage: HTMLElement;
  feedPulse: HTMLElement;
  lastUpdated: HTMLElement;
  refreshScores: HTMLButtonElement;
  heroMatchType: HTMLElement;
  heroHome: HTMLElement;
  heroHomeScore: HTMLElement;
  heroAway: HTMLElement;
  heroAwayScore: HTMLElement;
  heroStatus: HTMLElement;
  liveToggle: HTMLInputElement;
  balance: HTMLElement;
  loginButton: HTMLButtonElement;
  registerButton: HTMLButtonElement;
  accountButton: HTMLButtonElement;
  stake: HTMLInputElement;
  slipCount: HTMLElement;
  potentialReturn: HTMLElement;
  combinedMultiplier: HTMLElement;
  stakeHelp: HTMLElement;
  emptySlip: HTMLElement;
  slipItems: HTMLElement;
  placePrediction: HTMLButtonElement;
  clearSlip: HTMLButtonElement;
  openCount: HTMLElement;
  openPredictions: HTMLElement;
  slipPanel: HTMLElement;
  openPanel: HTMLElement;
  adminList: HTMLElement;
  auditLog: HTMLElement;
  marketControls: HTMLElement;
  liveCount: HTMLElement;
  suspendedCount: HTMLElement;
  linkedUserCount: HTMLElement;
  pendingTopUpCount: HTMLElement;
  adminPublicId: HTMLElement;
  copyAdminId: HTMLButtonElement;
  linkedUserList: HTMLElement;
  topUpRequestList: HTMLElement;
  adminDialog: HTMLDialogElement;
  adminForm: HTMLFormElement;
  adminName: HTMLInputElement;
  adminEmail: HTMLInputElement;
  adminRole: HTMLSelectElement;
  adminFormError: HTMLElement;
  authDialog: HTMLDialogElement;
  closeAuthDialog: HTMLButtonElement;
  loginForm: HTMLFormElement;
  loginKind: HTMLSelectElement;
  loginEmail: HTMLInputElement;
  loginPassword: HTMLInputElement;
  loginError: HTMLElement;
  registerForm: HTMLFormElement;
  registerName: HTMLInputElement;
  registerEmail: HTMLInputElement;
  registerPassword: HTMLInputElement;
  registerAdminId: HTMLInputElement;
  registerError: HTMLElement;
  profileDialog: HTMLDialogElement;
  profileName: HTMLElement;
  profileMeta: HTMLElement;
  profileBalance: HTMLElement;
  profilePredictionCount: HTMLElement;
  profileWonCount: HTMLElement;
  profileEarnings: HTMLElement;
  linkedAdminLabel: HTMLElement;
  profilePredictions: HTMLElement;
  walletActivity: HTMLElement;
  userProfileContent: HTMLElement;
  adminProfileContent: HTMLElement;
  addCoinsButton: HTMLButtonElement;
  logoutButton: HTMLButtonElement;
  topUpDialog: HTMLDialogElement;
  topUpForm: HTMLFormElement;
  topUpSxcAmount: HTMLInputElement;
  topUpPaymentAmount: HTMLElement;
  topUpPreview: HTMLElement;
  topUpQrImage: HTMLImageElement;
  topUpPreviewAmount: HTMLElement;
  topUpUpiId: HTMLElement;
  topUpRequestId: HTMLElement;
  walletAdjustmentDialog: HTMLDialogElement;
  walletAdjustmentForm: HTMLFormElement;
  walletAdjustmentUser: HTMLElement;
  walletAdjustmentUserId: HTMLInputElement;
  walletAdjustmentRequestId: HTMLInputElement;
  walletAdjustmentType: HTMLSelectElement;
  walletAdjustmentAmount: HTMLInputElement;
  walletAdjustmentNote: HTMLInputElement;
  walletAdjustmentError: HTMLElement;
  tourLayer: HTMLElement;
  tourCard: HTMLElement;
  tourProgress: HTMLElement;
  tourTitle: HTMLElement;
  tourBody: HTMLElement;
  tourBack: HTMLButtonElement;
  tourNext: HTMLButtonElement;
  tourClose: HTMLButtonElement;
  toast: HTMLElement;
}

function required<T extends HTMLElement>(id: string): T {
  const element = document.getElementById(id);
  if (!element) throw new Error(`Required element #${id} was not found`);
  return element as T;
}

export function getAppElements(): AppElements {
  return {
    sportsView: required('sports'),
    adminView: required('admin'),
    marketTitle: required('marketTitle'),
    scheduleFilters: required('scheduleFilters'),
    eventSummary: required('eventSummary'),
    eventList: required('eventList'),
    feedLabel: required('feedLabel'),
    feedMessage: required('feedMessage'),
    feedPulse: required('feedPulse'),
    lastUpdated: required('lastUpdated'),
    refreshScores: required<HTMLButtonElement>('refreshScores'),
    heroMatchType: required('heroMatchType'),
    heroHome: required('heroHome'),
    heroHomeScore: required('heroHomeScore'),
    heroAway: required('heroAway'),
    heroAwayScore: required('heroAwayScore'),
    heroStatus: required('heroStatus'),
    liveToggle: required<HTMLInputElement>('liveToggle'),
    balance: required('balance'),
    loginButton: required<HTMLButtonElement>('loginButton'),
    registerButton: required<HTMLButtonElement>('registerButton'),
    accountButton: required<HTMLButtonElement>('accountButton'),
    stake: required<HTMLInputElement>('stake'),
    slipCount: required('slipCount'),
    potentialReturn: required('potentialReturn'),
    combinedMultiplier: required('combinedMultiplier'),
    stakeHelp: required('stakeHelp'),
    emptySlip: required('emptySlip'),
    slipItems: required('slipItems'),
    placePrediction: required<HTMLButtonElement>('placePrediction'),
    clearSlip: required<HTMLButtonElement>('clearSlip'),
    openCount: required('openCount'),
    openPredictions: required('openPredictions'),
    slipPanel: required('slipPanel'),
    openPanel: required('openPanel'),
    adminList: required('adminList'),
    auditLog: required('auditLog'),
    marketControls: required('marketControls'),
    liveCount: required('liveCount'),
    suspendedCount: required('suspendedCount'),
    linkedUserCount: required('linkedUserCount'),
    pendingTopUpCount: required('pendingTopUpCount'),
    adminPublicId: required('adminPublicId'),
    copyAdminId: required<HTMLButtonElement>('copyAdminId'),
    linkedUserList: required('linkedUserList'),
    topUpRequestList: required('topUpRequestList'),
    adminDialog: required<HTMLDialogElement>('adminDialog'),
    adminForm: required<HTMLFormElement>('adminForm'),
    adminName: required<HTMLInputElement>('adminName'),
    adminEmail: required<HTMLInputElement>('adminEmail'),
    adminRole: required<HTMLSelectElement>('adminRole'),
    adminFormError: required('adminFormError'),
    authDialog: required<HTMLDialogElement>('authDialog'),
    closeAuthDialog: required<HTMLButtonElement>('closeAuthDialog'),
    loginForm: required<HTMLFormElement>('loginForm'),
    loginKind: required<HTMLSelectElement>('loginKind'),
    loginEmail: required<HTMLInputElement>('loginEmail'),
    loginPassword: required<HTMLInputElement>('loginPassword'),
    loginError: required('loginError'),
    registerForm: required<HTMLFormElement>('registerForm'),
    registerName: required<HTMLInputElement>('registerName'),
    registerEmail: required<HTMLInputElement>('registerEmail'),
    registerPassword: required<HTMLInputElement>('registerPassword'),
    registerAdminId: required<HTMLInputElement>('registerAdminId'),
    registerError: required('registerError'),
    profileDialog: required<HTMLDialogElement>('profileDialog'),
    profileName: required('profileName'),
    profileMeta: required('profileMeta'),
    profileBalance: required('profileBalance'),
    profilePredictionCount: required('profilePredictionCount'),
    profileWonCount: required('profileWonCount'),
    profileEarnings: required('profileEarnings'),
    linkedAdminLabel: required('linkedAdminLabel'),
    profilePredictions: required('profilePredictions'),
    walletActivity: required('walletActivity'),
    userProfileContent: required('userProfileContent'),
    adminProfileContent: required('adminProfileContent'),
    addCoinsButton: required<HTMLButtonElement>('addCoinsButton'),
    logoutButton: required<HTMLButtonElement>('logoutButton'),
    topUpDialog: required<HTMLDialogElement>('topUpDialog'),
    topUpForm: required<HTMLFormElement>('topUpForm'),
    topUpSxcAmount: required<HTMLInputElement>('topUpSxcAmount'),
    topUpPaymentAmount: required('topUpPaymentAmount'),
    topUpPreview: required('topUpPreview'),
    topUpQrImage: required<HTMLImageElement>('topUpQrImage'),
    topUpPreviewAmount: required('topUpPreviewAmount'),
    topUpUpiId: required('topUpUpiId'),
    topUpRequestId: required('topUpRequestId'),
    walletAdjustmentDialog: required<HTMLDialogElement>('walletAdjustmentDialog'),
    walletAdjustmentForm: required<HTMLFormElement>('walletAdjustmentForm'),
    walletAdjustmentUser: required('walletAdjustmentUser'),
    walletAdjustmentUserId: required<HTMLInputElement>('walletAdjustmentUserId'),
    walletAdjustmentRequestId: required<HTMLInputElement>('walletAdjustmentRequestId'),
    walletAdjustmentType: required<HTMLSelectElement>('walletAdjustmentType'),
    walletAdjustmentAmount: required<HTMLInputElement>('walletAdjustmentAmount'),
    walletAdjustmentNote: required<HTMLInputElement>('walletAdjustmentNote'),
    walletAdjustmentError: required('walletAdjustmentError'),
    tourLayer: required('tourLayer'),
    tourCard: required('tourCard'),
    tourProgress: required('tourProgress'),
    tourTitle: required('tourTitle'),
    tourBody: required('tourBody'),
    tourBack: required<HTMLButtonElement>('tourBack'),
    tourNext: required<HTMLButtonElement>('tourNext'),
    tourClose: required<HTMLButtonElement>('tourClose'),
    toast: required('toast')
  };
}
